apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      # For auto-scaling demo purposes via load test, here we ask to scale up already when 25% of CPU is utilized
      # (to avoid overloading the workshop k8s cluster)
      # but normally you would set it to ca 80 to 100 percents
      # (depending on weather you want to optimize for the processing speed for unexpected load peaks or saving cost)
      targetAverageUtilization: 25 # exceeding this % of container `resources.requests.cpu` will trigger autoscaling after a while
